### ISSUE TITLE
Question on "valid pair" concept

### ISSUE THREAD

**Issue by pollicipes** [ClaireMarchal/HiCRes#1]
Dear Claire,

First of all, congratulations for this wonderful piece of software. Just what we needed. :)

I have a small doubt on the concept of "valid pairs" that HiCRes uses. I am using HiCRes to determine the resolution of an experiment performed in an organism which is not neither human nor mouse. Thus, I have to start from a `bam` file containing those "valid pairs" that HiCRes needs. So, my question is the following:
Does this file have to contain those pairs of reads that have both mapped or should it be further filtered?

I set an example, for clarity: I processed my data with TADbit (Serra et al., 2017, PLoS Comp Bio). On a first step, TADbit generates a bam with ONLY all reads for which both reads have mapped, but, at the same time these reads could (and will) be classified into further categories, so you can filter them out. Namely:
- Random breaks
- Duplicates
- Dangling ends
- Self circles...
- etc.
Still, as I am saying, the reads in these categories have both their pairs mapped.

So should I use as a bam input this file filtered out for all this stuff above, or should be left "as is" to be given as input to HiCRes? I can easily clean out all these and left only the pairs I consider as "valid". Just let me know which is your exact concept of "valid pairs". :)

Thank you!!
Best,
Juan

**Comment by ClaireMarchal** [comment]
Hi Juan,

Thank you for your nice comment!

HiCRes uses valid interactions which are the filtered ones. Which means you need to provide a bam that has been filtered for all the bad interactions you listed above (the tool HICUP can do this). Using this bam, HiCRes will output the predictions of the resolution using all these interactions (inter- and intra-chromosomal), as well as the resolution using the cis (intra-chromosomal) interactions only.

To note, a version coming soon will also output the resolution using only the cis-far (intra-chromosomal, >10kb) interactions, which are usually the most relevant to determine chromatin structure (loops / TADs...).

Finally another thing: we are testing other species in addition to Human and Mouse, and have been successful at predicting the resolution for A. thaliana Hi-C as well as D. melanogaster Hi-C. Curiously, the predictions for the C. elegans dataset we tested seem not to be very accurate, we are still troubleshooting for this species.

Good luck with your experiments!

Claire

**Comment by pollicipes** [comment]
Hi Claire!
Thank you for your detailed response! That clearly answers my question. 
Just to add on this _C.elegans_ issue, I am working with birds and some of them turn to have some very small chromosomes (< 2 Mb). This leads me to think... could chromosome size be biasing somehow your predictions on _C.elegans_?

Anyway, looking forward to that new version coming! :)
Congratulations again!

Best,
J
