### ISSUE TITLE
Questions about the file input and installation?

### ISSUE THREAD

**Issue by Linhua-Sun** [ClaireMarchal/HiCRes#2]
Hello, we have recently noticed your article published in Nucleic Acids Research and have good opinions on Hi-C resolutions; I'd like to ask if you can directly analyze and calculate the Hi-C resolution through `cooler` or other popular formats; In addition, is there any instruction document for installation of the software? Thank you!

**Comment by ClaireMarchal** [comment]
Hi,
Thank you for your interest!

Unfortunately, HiCRes doesn't use .cool or .hic file as input. It needs the valid aligned reads to generate a model for the submitted  sample. Alignment information is lost in these file formats. Nevertheless, we will develop the usage of .cool and .hic files as HiCRes input in the near future. 

To use HiCRes, you need to install either [docker](docs.docker.com/get-docker/) or [singularity](sylabs.io/guides/3.0/user-guide/installation.html) then follow the HiCRes [readme](github.com/ClaireMarchal/HiCRes).

**Comment by Linhua-Sun** [comment]
Thanks for you kindly reply. It helps. We look forward to your new updates using cooler format.
