### ISSUE TITLE
ValidPairs.bam

### ISSUE THREAD

**Issue by Nuturetree** [ClaireMarchal/HiCRes#3]
Dear Claire,

I want to know how to combine the HiC-Pro result. I can produce the **.allValidPairs file, but I do not know how to transit become the ValidPairs.bam file. can you give me some suggestions to resolve this problem?

**Comment by ClaireMarchal** [comment]
Hello,
Sorry, the answer comes really late, but just in case it could help someone else, here is a suggestion.
I think you can generate a pseudo bam file to give to HiCRes. HiCRes uses only the column 3, 4, 7 and 8 of the bam file, which are the chr1, position1, chr2 ("=" if this is the same as chr1) and position2 respectively. HiCRes uses samtools view to open the bam file, which means your pseudo bam will need to be able to be opened by samtools.
