### ISSUE TITLE
Predicted and observed resolutions don't match

### ISSUE THREAD

**Issue by aminakur** [ClaireMarchal/HiCRes#5]
I calculated the resolution for my library using .bam file of 253M valid read pairs. The observed resolution was estimated as 2bp. However, the predicted resolution for this library size is 1780bp. 

HiCRes output:
```
Prediction table generation
************************************************************

The resolution of your libary is 2 bp (using all interactions).

null device
          1
```
prediction.txt:
```
250000000       1797.46012572308
251000000       1791.87081570268
252000000       1786.32260659004
253000000       1780.81503159021
254000000       1775.34763104804
```
prediction.png
![prediction az_mrg](https://user-images.githubusercontent.com/85445902/203813249-b6effb5c-b8b9-4e51-8d9a-f0bc4b139029.png)

How can you interpret this?

**Comment by ClaireMarchal** [comment]
Hello,
I was not able to reproduce the issue with other datasets.  I'm not certain why the printing of the data resolution on the terminal was incorrect. My guess is that it may have to do with a rounding problem, but without a way to reproduce it, it will be difficult to test.
You need to use the resolution computed in the prediction.txt table.
